---
title: "India_nutrition"
output: html_document
date: "2022-11-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Load libraries

library(tidyverse)
library(here)
library(viridis)
library(sf)
library(ggpp)
```


```{r}
#Load the subnational dataset for pakistan and Ethiopia

library(readxl)
datapakethind <- read_excel("20221125_wdp_data.xlsx", sheet = 2)

datapakethind
```
```{r}
#Filter relevant columns

datapakethind %>% 
    filter(`Age Group` %in% c("15-30", "30-45") & Gender == "female" & Year %in% c(2022, 2030) & `Daily Spending Bracket` %in% c("$0-2", "$2-5", "$5-8", "$8-12")) %>% 
    group_by(`Country / Region`, Year) %>% 
    summarise(Totpop = sum(Population))
```


```{r}

# Load the subnational dataset for india

df <- read.csv("india_state_level_numbers_2020_to_2030.csv")

glimpse(df)
```

```{r}
df %>% 
     filter(age_group %in% c("[15,20)", "[20,25)", "[25,30)", "[30,35)", "	[35,40)", "[40,45)") & gender == 2 & year == 2030 & spending_group == "[0,11)")  %>% 
    summarize(count = sum(population))
    
```
```{r}
#Scale 2022 data 

df2022scaled <- df %>% 
    group_by(state_name, gender, age_group,year, spending_group) %>% 
    filter(age_group %in% c("[15,20)", "[20,25)", "[25,30)", "[30,35)", "	[35,40)", "[40,45)") & gender == 2 & year == 2022 & spending_group == "[0,11)")  %>% 
    summarise(Totpop = sum(population)) %>% 
    mutate(Totadjpop = Totpop * 1.1167499) %>% 
    ungroup()

```
```{r}
#Scale 2030 data

df2030scaled <- df %>% 
    group_by(state_name, gender, age_group,year, spending_group) %>% 
    filter(age_group %in% c("[15,20)", "[20,25)", "[25,30)", "[30,35)", "	[35,40)", "[40,45)") & gender == 2 & year == 2030 & spending_group == "[0,11)")  %>% 
    summarise(Totpop = sum(population)) %>% 
    mutate(Totadjpop = Totpop * 1.16585) %>% 
    ungroup()

df2030scaled
```


```{r}

#Check
df2030scaled %>% 
    filter(age_group %in% c("[15,20)", "[20,25)", "[25,30)", "[30,35)", "	[35,40)", "[40,45)") & gender == 2 & year == 2030 & spending_group == "[0,11)")  %>% 
    summarise(sum = sum(Totadjpop))
```


```{r}
#Read shape file


shape_india <- read_sf("ind_state_level.shp")

shape_india

```


```{r}
# Filter for women aged 15-45 years earning less than 11USD  for 2022

data_india2022 <- df2022scaled %>% 
    group_by(state_name) %>% 
    summarise(Vulnerablegroup = sum(Totadjpop)) %>% 
    mutate(percentvulnerable = Vulnerablegroup/ sum(Vulnerablegroup) * 100) %>% 
    ungroup()

data_india2022

```
```{r}
# Plot heat map

my_path <- "\\Users\\Linda Karani\\Documents\\gitrepo\\Fertility-rates-India"
options(scipen=999, digits = 2)


spatialdataind2022 <- merge(shape_india, data_india2022, by = "state_name")


spatialdataind2022 %>%
  ggplot() + 
  geom_sf(mapping = aes(fill = Vulnerablegroup), show.legend = TRUE) +
  coord_sf()+
  scale_fill_viridis_c(option = "A") + labs(title = "Total population of vulnerable child bearing women in 2022")
  
ggsave("Total population of child bearing women in 2022.png", path = my_path, width = 6, height = 4.5)
```
```{r}
# Plot heatmap showing percentage

spatialdataind2022 %>%
    ggplot() + 
    geom_sf(mapping = aes(fill = percentvulnerable), show.legend = TRUE) +
    coord_sf()+
    scale_fill_viridis_c(option = "A") + labs(title = "Percentage of vulnerable child bearing women in 2022")
  
ggsave("Percentage of child bearing women in 2022.png", path = my_path, width = 6, height = 4.5)

```




```{r}
# Filter for women aged 15-45 years earning less than 11USD  for 2030

data_india2030 <- df2030scaled %>% 
    group_by(state_name) %>% 
    summarise(Vulnerablegroup = sum(Totadjpop)) %>% 
    mutate(percentvulnerable = Vulnerablegroup/ sum(Vulnerablegroup) * 100) %>% 
    ungroup()

data_india2030
```

```{r}
# Plot heat map

my_path <- "\\Users\\Linda Karani\\Documents\\gitrepo\\Fertility-rates-India"
options(scipen=999, digits = 2)


spatialdataind2030 <- merge(shape_india, data_india2030, by = "state_name")


spatialdataind2030 %>%
  ggplot() + 
  geom_sf(mapping = aes(fill = Vulnerablegroup), show.legend = TRUE) +
  coord_sf()+
  scale_fill_viridis_c(option = "A") + labs(title = "Total population of vulnerable child bearing women in 2030")
  
ggsave("Total population of child bearing women in 2030.png", path = my_path, width = 6, height = 4.5)

```





```{r}
spatialdataind2030 %>%
    ggplot() + 
    geom_sf(mapping = aes(fill = percentvulnerable), show.legend = TRUE) +
    coord_sf()+
    scale_fill_viridis_c(option = "A") + labs(title = "Percentage of vulnerable child bearing women in 2030")
  
ggsave("Percentage of child bearing women in 2030.png", path = my_path, width = 6, height = 4.5)

```
```{r}
#Compare India, Ethiopia and Pakistan – is percentage increase in vulnerable pregnant/lactacting women from 2022 to 2030 similar? (Or just child-bearing age women if fertility rates are not available for 2030)

datapakethind_plot <- datapakethind %>% 
    filter(`Age Group` %in% c("15-30", "30-45") & Gender == "female" & Year %in% c(2022, 2030) & `Daily Spending Bracket` %in% c("$0-2", "$2-5", "$5-8", "$8-12")) %>% 
    group_by(`Country / Region`, Year) %>% 
    summarise(Totpop = sum(Population)) %>% 
    ungroup()

datapakethind_plot %>% 
    write_csv( "datapakindplot_comparison.csv")

```

```{r}
#How many of these women are pregnant or lactating (try to calculate using fertility rate), and how many of these are vulnerable (calculate total number, income group 0-11USD)

data_all <- datapakethind %>% 
    filter(`Age Group` %in% c("15-30", "30-45") & Gender == "female" & Year %in% c(2022, 2030) & `Daily Spending Bracket` == "ALL" )%>% 
    group_by(`Country / Region`, Year) %>% 
    summarise(Totpop = sum(Population)) %>% 
    ungroup()


data_vulnerable <- datapakethind %>% 
    filter(`Age Group` %in% c("15-30", "30-45") & Gender == "female" & Year %in% c(2022, 2030) & `Daily Spending Bracket` %in% c("$0-2", "$2-5", "$5-8", "$8-12"))%>% 
    group_by(`Country / Region`, Year) %>% 
    summarise(Totvulnerable = sum(Population)) %>% 
    ungroup()

data_join <- data_all %>% 
    left_join(data_vulnerable, by = c("Country / Region" = "Country / Region", "Year" = "Year")) %>% 
    filter(Year == 2022) %>% 
    pivot_longer(cols = c("Totpop", "Totvulnerable"), names_to = "Population", values_to = "Value")

```

```{r}
#Plot Ethiopia

data_join %>% 
    filter(`Country / Region` == "Ethiopia") %>% 
     ggplot(aes(x = reorder(`Country / Region`, -Value),
               y = Value,
               fill = as.factor(Population))
           ) +
    geom_col(position = "dodge") +
    geom_text(aes(label = round(Value)) , vjust = -0.2, size = 3, position = position_dodge(.9) ) +
    theme_bw()+
    labs(title = "Comparison of total child bearing women vs Vulnerable women in Ethiopia", fill = "Year") + xlab("Country") + ylab("Total population/Vulnerable of women aged 15-45")  +
    scale_fill_manual(values = c("#004561", "#5891ad"))+
    theme(axis.text = element_text(size = 9),
          axis.title = element_text(size = 9),
          legend.text = element_text(size = 9))

ggsave("Comparison of total child bearing women vs Vulnerable women in Ethiopia.png", path = my_path, width = 8, height = 4.5)
    

```
```{r}
#Plot India

data_join %>% 
    filter(`Country / Region` == "India") %>% 
     ggplot(aes(x = reorder(`Country / Region`, -Value),
               y = Value,
               fill = as.factor(Population))
           ) +
    geom_col(position = "dodge") +
    geom_text(aes(label = round(Value)) , vjust = -0.2, size = 3, position = position_dodge(.9) ) +
    theme_bw()+
    labs(title = "Comparison of total child bearing women vs Vulnerable women in India", fill = "Year") + xlab("Country") + ylab("Total population/Vulnerable of women aged 15-45")  +
    scale_fill_manual(values = c("#004561", "#5891ad"))+
    theme(axis.text = element_text(size = 9),
          axis.title = element_text(size = 9),
          legend.text = element_text(size = 9))

ggsave("Comparison of total child bearing women vs Vulnerable women in India.png", path = my_path, width = 8, height = 4.5)
    

```



```{r}
# Compute growth rate from 2022 to 2030

dataperc <- datapakethind_plot %>% 
    pivot_wider(names_from = Year, values_from = Totpop) %>% 
    mutate(perc = ((`2030` - `2022`)/`2022`) *100) %>% 
    pivot_longer(cols = c("2022", "2030"), names_to = "Year")

dataperc
 
```


```{r}

options(scipen=999, digits = 2)
dataperc%>%
    ggplot(aes(x = reorder(`Country / Region`, -value),
               y = value,
               fill = as.factor(Year))
           ) +
    geom_col(position = "dodge") +
    geom_text(aes(label = round(value)) , vjust = -0.2, size = 3, position = position_dodge(.9) ) +
    theme_bw()+
    labs(title = "Vulnerable child bearing women in India, Ethiopia and Pakistan", fill = "Year") + xlab("Country") + ylab("Total population of vulnerable women aged 15-45")  +
    scale_fill_manual(values = c("#004561", "#5891ad"))+
    theme(axis.text = element_text(size = 9),
          axis.title = element_text(size = 9),
          legend.text = element_text(size = 9))

ggsave("Comparison of child bearing women in India, Ethiopia and Pakistan.png", path = my_path, width = 8, height = 4.5)
    
```

